# Generated by Django 4.1.3 on 2023-07-19 15:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('createdBy', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('createdBy', models.TextField(max_length=30)),
                ('agency', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=30, unique=True)),
                ('id', models.CharField(default=api.models.key_generator, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
