# Generated by Django 4.1.1 on 2022-09-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('createdBy', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('createdBy', models.TextField(max_length=30)),
                ('agency', models.TextField(max_length=30)),
            ],
        ),
    ]
